### ISSUE TITLE
Percent-Encoding Normalization

### ISSUE THREAD

**Issue by 9hk** [fogfish/curie#31]
does this package offer IRI normalization? For example turning this:

 https://en.wiktionary.org/wiki/%E1%BF%AC%CF%8C%CE%B4%CE%BF%CF%82

into this:

https://en.wiktionary.org/wiki/Ῥόδος

refs:

https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier
https://www.ietf.org/rfc/rfc3987.html#section-5.3.2.3

**Comment by fogfish** [comment]
The library had support for percent encoding for encoding to URL (see `curie.URL`) but it did not have a support for decoding from URL (see `curie.FromURL`). Now, it has for both encoding/decoding.

Thank you for hint.
