### ISSUE TITLE
QueryUnescape assumes all values are printable

### ISSUE THREAD

**Issue by 9hk** [fogfish/curie#33]
Using this program:

~~~go
package main

import (
   "fmt"
   "github.com/fogfish/curie"
)

const wiki = "http://wiktionary.org/wiki/%E1%BF%AC%CF%8C%CE%B4%CE%BF%CF%82_%1F"

func main() {
   a := curie.Namespaces{"wiki": "http://wiktionary.org/wiki/"}.Create(wiki)
   fmt.Printf("%q\n", a) // "wiki:Ῥόδος_\x1f"
}
~~~

program chokes on the last value, instead of leaving it encoded. Other packages leave the value encoded, for example this Rust crate:

~~~rust
use iri_string::percent_encode::PercentEncoded;
use iri_string::spec::IriSpec;

fn main() {
   let dec = "/wiki/Ῥόδος\x1f😀";
   let enc = PercentEncoded::<_, IriSpec>::from_path(dec).to_string();
   dbg!(enc); // "/wiki/Ῥόδος%1F😀"
}
~~~

Probably this function need to be added:

https://godocs.io/unicode#IsGraphic

or maybe you could iterate the string and check against:

https://godocs.io/unicode/utf8#RuneError

**Comment by 9hk** [comment]
https://github.com/fogfish/curie/blob/4964c8f9043fb45994299af94c7d7aa8be9a3b71/curie.go#L91

**Comment by 9hk** [comment]
OK I think this does it. If you have a better method, feel free to use it instead:

~~~go
package url

import (
   "net/url"
   "strings"
   "unicode"
   "unicode/utf8"
)

func graphic(r rune) bool {
   if r == utf8.RuneError {
      return false
   }
   return unicode.IsGraphic(r)
}

func query_escape(s string) string {
   var str strings.Builder
   for i, r := range s {
      if graphic(r) {
         str.WriteRune(r)
      } else {
         esc := url.QueryEscape(s[i:i+1])
         str.WriteString(esc)
      }
   }
   return str.String()
}
~~~

**Comment by fogfish** [comment]
Thank you for hit! Let me explore this path!

**Comment by 9hk** [comment]
since the hex encoding is just a single byte, this might be a better option:

~~~go
package url
import "strings"

const upper_hex = "0123456789ABCDEF"

func query_escape(s string) string {
   var str strings.Builder
   for index, r := range s {
      if graphic(r) {
         str.WriteRune(r)
      } else {
         b := s[index]
         str.WriteByte('%')
         str.WriteByte(upper_hex[b>>4])
         str.WriteByte(upper_hex[b&0xF])
      }
   }
   return str.String()
}
~~~

**Comment by fogfish** [comment]
One challenge that pops here! The `URI -> IRI` algorithm as defined by https://www.rfc-editor.org/rfc/rfc3987#section-3.2 requires:

> Convert all percent-encodings ("%" followed by two hexadecimal digits) to the corresponding octets, except those corresponding to "%", characters in "reserved", and characters in US-ASCII not allowed in URIs.

but built-in url.Escape / url.Unescape functions does not support it well. Custom escaping makes it working. Feel free to check linked PR.

**Comment by 9hk** [comment]
one issue I just realized. If the rune is not `utf8.RuneError`, and the rune is not graphic, it can still be one:

~~~
U+0000
~~~

or more bytes:

~~~
U+0378
~~~

so you cant assume a single byte as in my previous example

**Comment by 9hk** [comment]
OK I tried some more combinations, I think I like this:

~~~go
package url

import (
   "net/url"
   "unicode"
   "unicode/utf8"
)

func is_graphic(r rune) bool {
   if r == '%' {
      return false
   }
   if r == utf8.RuneError {
      return false
   }
   return unicode.IsGraphic(r)
}

func query_escape(s string) string {
   var vals []byte
   for len(s) >= 1 {
      r, size := utf8.DecodeRuneInString(s)
      var val string
      if is_graphic(r) {
         val = s[:size]
      } else {
         val = url.QueryEscape(s[:size])
      }
      vals = append(vals, val...)
      s = s[size:]
   }
   return string(vals)
}
~~~

**Comment by fogfish** [comment]
This looks nice! Unfortunately, it would not handle properly **reserved** characters. Please check `codec.go` it makes a compliant URI -> IRI decoder. In case of IRI -> URI, built-in url codec works fine I believe.
